# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  install-deps-cmd:
    steps:
      - run: npm ci
  run-unit-tests-cmd:
    steps:
      - run: npm run test
  build-project-cmd:
    steps:
      - run: npm run build

executors:
  node-docker-with-aws:
    docker:
      - image: mjfreed/circleci-images:0.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  install-deps:
    executor: node-docker-with-aws
    working_directory: ~/react-website
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - install-deps-cmd
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  test:
    executor: node-docker-with-aws
    working_directory: ~/react-website
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run-unit-tests-cmd
  build:
    executor: node-docker-with-aws
    working_directory: ~/react-website
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - build-project-cmd

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-project:
    jobs:
      - install-deps
      - test:
          requires:
          - install-deps
      - build:
          requires:
          - test
